import turtle
turtle.Screen().bgcolor("Orange")
board = turtle.Turtle()
#Triangle
board.forward(100)
board.left(120)
board.forward(100)
board.left(120)
board.forward(100)
board.penup()
board.right(90)
board.forward(100)
# Triangle
board.pendown()
board.right(90)
board.forward(100)
board.right(120)
board.forward(100)
board.right(120)
board.forward(100)
turtle.done()